# Generated by Django 5.1.4 on 2025-01-28 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_bankaccount_currency_alter_transaction_amount"),
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VirtualCar",
            new_name="VirtualCard",
        ),
    ]
