# Generated by Django 5.1.4 on 2024-12-30 18:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+4915123456789",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
