# Generated by Django 5.1.4 on 2025-01-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_profile_account_currency_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("euro", "Euro"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
    ]
