# Generated by Django 5.1.4 on 2025-01-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("us_dollar", "Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("euro", "Euro"),
                ],
                max_length=20,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Amount"
            ),
        ),
    ]
