# Generated by Django 5.1.4 on 2025-01-22 02:16

import core_apps.user_auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core_apps.user_auth.managers.UserManager()),
            ],
        ),
    ]
